### ISSUE TITLE
About code Publishing

### ISSUE THREAD

**Issue by leduo1** [liuxinhai/SPU-Net#2]
Hi! Thank you for your great work.

I want to know when will you release the code?

**Comment by liuxinhai** [comment]
Sorry，I'm a little busy recently. I will release the code as soon as possible.

________________________________
发件人: leduo1 ***@***.***>
发送时间: 2022年7月29日 9:37
收件人: liuxinhai/SPU-Net ***@***.***>
抄送: Subscribed ***@***.***>
主题: [liuxinhai/SPU-Net] About code Publishing (Issue #2)


Hi! Thank you for your great work.

I want to know when will you release the code?

―
