### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by LiXiangDeng** [liuxinhai/SPU-Net#4]
您好 我看到您的论文效果十分好 但是在您的训练数据集这里我还有一些疑问  请问您是如何处理您的训练数据集的呢  是在pugan的mesh上重新采样2048个点 分成24个patch 得到256个点 在放到您的网络里 分成64个点去训练吗

**Comment by liuxinhai** [comment]
Please  refer to the training and test data in this link: https://drive.google.com/drive/folders/1pMf-brvyzoBBM-EkPncUhIt3yQWMTpvx?usp=sharing
